---
- name: ensure logs are readable
  delegate_to: localhost
  command: "chmod -R u=rwX,g=rX,o=rX {{ zuul.executor.log_root }}/"

- name: put logs in /opt/zuul
  synchronize:
    src: "{{ zuul.executor.log_root }}/"
    dest: "/opt/zuul/{{ zuul.build }}"
