---
- name: create file
  file:
    path: /home/gabriel/pre-role-one.txt
    state: touch

- name: get zuul content
  copy:
    content: "{{ zuul | to_nice_yaml }}"
    dest: /home/gabriel/pre-role-one.txt
